### ISSUE TITLE
Initial release 🎉 (v0.1.0) roadmap/todo list

### ISSUE THREAD

**Issue by ricokahler** [JustSift/ReSift#6]
Stability is something we care about deeply with this library so it's important for us to have a plan/todo list that includes everything that's required in order to finish the initial release of this library.

The good news is that the code for this library is done (since we use it in production at Sift), however there is still a list of things to complete for our initial release.

Here's that list:

- [x] Documentation of main concepts and main APIs (most effort by far) See https://github.com/JustSift/ReSift/issues/7
- [x] New README
- [x] Automatic API documentation generation + JS doc audit + integration with docusaurus
- [x] Test coverage > 95% (ideally 100%). See https://github.com/JustSift/ReSift/pull/11
- [x] Coveralls + Travis integration
- [x] API audit for older terminology before fetch factories and fetches instances (any terminology that uses "action creators" should be removed)
- [x] Add eslint back in + linting audit using `react-hooks/exhaustive-deps`
- [x] Typings audit
- [x] Semi-permanent logo + colors
- [ ] (nice-to-have) Tutorial using ReSift Rentals
- [x] #21 
- [x] #23
- [x] #22 
- [x] SEO audit

Please let me know if there is anything else missing for this list or if you have any insight in any of the tasks above.

Thanks everyone!

**Comment by JulesPatry** [comment]
👍
